# Generated by Django 4.2.4 on 2024-01-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='reference',
            field=models.URLField(blank=True, default='https://www.google.com', null=True),
        ),
    ]
