# Generated by Django 4.2.4 on 2023-11-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=5000)),
                ('keyword', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_link', models.CharField(max_length=5000)),
                ('date_posted', models.DateField()),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=150, null=True)),
                ('job_function', models.CharField(blank=True, max_length=150, null=True)),
                ('industries', models.CharField(blank=True, max_length=150, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=150, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.field')),
            ],
        ),
    ]
