# Generated by Django 4.2.7 on 2023-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=5000)),
                ('keyword', models.CharField(max_length=100)),
                ('keyword_id', models.IntegerField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_link', models.CharField(max_length=5000)),
                ('date_posted', models.DateField()),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=150, null=True)),
                ('job_function', models.CharField(blank=True, max_length=150, null=True)),
                ('industries', models.CharField(blank=True, max_length=150, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=150, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
