
# Generated by Django 4.2.4 on 2023-12-13 04:13


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques1', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=100, verbose_name='1. What is your current academic status?')),
                ('ques2', models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science')], max_length=100, verbose_name='2. What was your academic course during your studies?')),
                ('ques3', models.CharField(choices=[('1', 'Not Accurate'), ('2', 'Somewhat Accurate'), ('3', 'Neutral'), ('4', 'Accurate'), ('5', 'Very Accurate')], max_length=100, verbose_name='3. On a scale of 1 to 5, how accurate do you find the systems recommendations in line with your academic interests and career goals? (1 - Not Accurate, 5 - Very Accurate)')),
                ('ques4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='4. Have you encountered any challenges or discrepancies with the recommendations provided by the system?')),
                ('ques5', models.CharField(choices=[('Extremely Influential', 'Extremely Influential'), ('Moderately Influential', 'Moderately Influential'), ('Slightly Influential', 'Slightly Influential'), ('Not Influential at All', 'Not Influential at All')], max_length=100, verbose_name='5. To what extent do you feel the recommendation system has positively influenced your academic and career-related decisions?')),
                ('ques6', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, verbose_name='6. On a scale of 1 to 5, how user-friendly do you find the recommendation system interface? (1 - Not User-Friendly, 5 - Very User-Friendly)')),
                ('ques7', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='7. Would you recommend this recommendation system to your peers or colleagues in IT/CS?')),
                ('recommendation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.userrecommendations')),
            ],
        ),
    ]
