# Generated by Django 4.2.4 on 2023-11-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('university', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=3000)),
                ('skills', models.CharField(max_length=1000)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.field')),
            ],
        ),
    ]
