# Generated by Django 4.2.7 on 2024-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isvarified',
            field=models.BooleanField(default=False),
        ),
    ]
