# Generated by Django 4.2.4 on 2023-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_learningmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
