# Generated by Django 4.2.7 on 2023-11-24 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science')], max_length=100, verbose_name='1. What was your academic specialization?')),
                ('q2', models.CharField(choices=[('Completely Aligned', 'Completely Aligned'), ('Mostly Aligned', 'Mostly Aligned'), ('Somewhat Aligned', 'Somewhat Aligned'), ('Not Aligned at All', 'Not Aligned at All')], max_length=100, verbose_name='2. To what extent do you feel your academic specialization aligns with your current job responsibilities?')),
                ('q3', models.CharField(choices=[('Very Well', 'Very Well'), ('Well', 'Well'), ('Neutral', 'Neutral'), ('Poorly', 'Poorly'), ('Not at All', 'Not at All')], max_length=100, verbose_name='3. How well did your academic specialization prepare you for your current role?')),
                ('q4', models.BooleanField(verbose_name='4. Have you pursued any additional certifications or training after graduation to enhance your skills for your current job?')),
                ('q5', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], max_length=100, verbose_name='5. In hindsight, do you think a different academic specialization might have better prepared you for your current career?')),
                ('q6', models.CharField(choices=[('Very Satisfied', 'Very Satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very Dissatisfied', 'Very Dissatisfied')], max_length=100, verbose_name='6. How satisfied are you with your current job in terms of alignment with your academic specialization and overall career growth?')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
