# Generated by Django 4.2.4 on 2023-12-13 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science')], default='IT', max_length=100, verbose_name='1. What was your academic specialization?')),
                ('q2', models.CharField(choices=[('Completely Aligned', 'Completely Aligned'), ('Mostly Aligned', 'Mostly Aligned'), ('Somewhat Aligned', 'Somewhat Aligned'), ('Not Aligned at All', 'Not Aligned at All')], default='Completely Aligned', max_length=100, verbose_name='2. To what extent do you feel your academic specialization aligns with your current job responsibilities?')),
                ('q3', models.CharField(choices=[('Very Well', 'Very Well'), ('Well', 'Well'), ('Neutral', 'Neutral'), ('Poorly', 'Poorly'), ('Not at All', 'Not at All')], default='Very Well', max_length=100, verbose_name='3. How well did your academic specialization prepare you for your current role?')),
                ('q4', models.BooleanField(default=False, verbose_name='4. Have you pursued any additional certifications or training after graduation to enhance your skills for your current job?')),
                ('q5', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default='No', max_length=100, verbose_name='5. In hindsight, do you think a different academic specialization might have better prepared you for your current career?')),
                ('q6', models.CharField(choices=[('Very Satisfied', 'Very Satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very Dissatisfied', 'Very Dissatisfied')], default='Satisfied', max_length=100, verbose_name='6. How satisfied are you with your current job in terms of alignment with your academic specialization and overall career growth?')),
                ('q7', models.CharField(choices=[('Software Development', 'Software Development'), ('Data Analytics', 'Data Analytics'), ('Design & UI', 'Design & UI'), ('Product Management', 'Product Management'), ('Testing and Quality Assurance', 'Testing and Quality Assurance'), ('Security', 'Security')], default='Software Development', max_length=100, verbose_name='7. What was the final field recommendation to you by our system?')),
                ('q8', models.CharField(choices=[('Software Development', 'Software Development'), ('Data Analytics', 'Data Analytics'), ('Design & UI', 'Design & UI'), ('Product Management', 'Product Management'), ('Testing and Quality Assurance', 'Testing and Quality Assurance'), ('Security', 'Security')], default='Software Development', max_length=100, verbose_name='8. What field is your job currently aligned on?')),
                ('q9', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100, verbose_name='9. Sex:')),
                ('q10', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=100, verbose_name='10. Civil Status:')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
