# Generated by Django 4.2.7 on 2023-11-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='q10',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=100, verbose_name='10. Civil Status:'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q7',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Data Analytics', 'Data Analytics'), ('Design & UI', 'Design & UI'), ('Product Management', 'Product Management'), ('Testing and Quality Assurance', 'Testing and Quality Assurance'), ('Security', 'Security')], default='Software Development', max_length=100, verbose_name='7. What was the final field recommendation to you by our system?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q8',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Data Analytics', 'Data Analytics'), ('Design & UI', 'Design & UI'), ('Product Management', 'Product Management'), ('Testing and Quality Assurance', 'Testing and Quality Assurance'), ('Security', 'Security')], default='Software Development', max_length=100, verbose_name='8. What field is your job currently aligned on?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q9',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100, verbose_name='9. Sex:'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q1',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science')], default='IT', max_length=100, verbose_name='1. What was your academic specialization?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q2',
            field=models.CharField(choices=[('Completely Aligned', 'Completely Aligned'), ('Mostly Aligned', 'Mostly Aligned'), ('Somewhat Aligned', 'Somewhat Aligned'), ('Not Aligned at All', 'Not Aligned at All')], default='Completely Aligned', max_length=100, verbose_name='2. To what extent do you feel your academic specialization aligns with your current job responsibilities?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q3',
            field=models.CharField(choices=[('Very Well', 'Very Well'), ('Well', 'Well'), ('Neutral', 'Neutral'), ('Poorly', 'Poorly'), ('Not at All', 'Not at All')], default='Very Well', max_length=100, verbose_name='3. How well did your academic specialization prepare you for your current role?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q4',
            field=models.BooleanField(default=False, verbose_name='4. Have you pursued any additional certifications or training after graduation to enhance your skills for your current job?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default='No', max_length=100, verbose_name='5. In hindsight, do you think a different academic specialization might have better prepared you for your current career?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q6',
            field=models.CharField(choices=[('Very Satisfied', 'Very Satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very Dissatisfied', 'Very Dissatisfied')], default='Satisfied', max_length=100, verbose_name='6. How satisfied are you with your current job in terms of alignment with your academic specialization and overall career growth?'),
        ),
    ]
